const PROJECTS = [
  {id:"mca",title:"Merchant Cash Advance",category:"professional",emoji:"💳",
   image:"assets/img/merchant_cash_advance.png",
   tagline:"Fintech platform generating USD 1M+ revenue at Grab",
   tags:["Deluge","Full-Stack","UX Design","FinTech","Singpass API"],
   metrics:[{v:"USD 1M+",l:"Revenue"},{v:"66%",l:"Loan Uplift"},{v:"Instant",l:"KYC via Singpass"}],
   overview:"Led development of the Merchant Cash Advance online flow at GrabFinance, integrated into Grab's existing business portal. Acted as full-stack developer, UX designer, UAT tester, and project contributor simultaneously.",
   problem:"Grab merchant-partners needed fast access to capital but the existing application process was slow and complex. Manual KYC took up to 2 days per application and loan uptake was low.",
   solution:"Built an end-to-end loan application flow using Deluge, integrated Singpass OAuth 2.0 for instant government-verified KYC, and led UX design with mockups presented to stakeholders before build.",
   impact:["USD 1,000,000+ in revenue generated through merchant loans","66% increase in loan take-up rate","KYC process reduced from up to 2 days to instant via Singpass","Conducted UAT with real merchants before full launch"],
   tech:["Deluge (Zoho)","HTML/CSS/JS","Singpass API","OAuth 2.0","RESTful APIs","Figma"],
   github:"",demo:"https://www.grab.com/sg/merchant/lending/easy-loans"},

  {id:"supplypay",title:"SupplyPay Platform",category:"professional",emoji:"🏦",
   image:"assets/img/supplypay_platform.jpg",
   tagline:"Lead developer · centralized portal automating multi-party transactions at GrabFinance",
   tags:["Deluge","Full-Stack","Automation","FinTech","Invoice Processing"],
   metrics:[{v:"Lead Dev",l:"Role"},{v:"95%",l:"Dev Ownership"},{v:"Full-Stack",l:"End-to-end"}],
   overview:"Led 95% of development on SupplyPay, a centralized portal automating transactions among Grab, suppliers, and merchants. Balanced development with UX design, marketing, and UAT across intense time constraints.",
   problem:"Invoice processing between Grab, suppliers, and merchants was entirely manual, causing delays, reconciliation errors, and operational inefficiency.",
   solution:"Architected a centralized portal handling automated invoice upload, payment workflows, tracking dashboards, and notifications. Wrote exhaustive requirements documentation covering all project phases from inception to delivery.",
   impact:["Streamlined invoice processing across all parties","Eliminated manual reconciliation errors","Delivered under tight deadlines while handling dev, design, and UAT concurrently","Participated in stand-ups with business teams to align technical and commercial priorities"],
   tech:["Deluge (Zoho)","Full-Stack","Workflow Automation","Dashboard Design","UX Mockups"],
   github:"",demo:""},

  {id:"asl",title:"ASL Letter Recognition",category:"ai-ml",emoji:"🤟",
   image:"assets/img/asl_recognition.gif",
   tagline:"Real-time sign language detection · 90.38% accuracy · PyTorch MLP",
   tags:["PyTorch","MediaPipe","Computer Vision","Flask","Python"],
   metrics:[{v:"90.38%",l:"Validation Accuracy"},{v:"87K+",l:"Training Images"},{v:"63-dim",l:"Feature Vector"}],
   overview:"Real-time ASL letter recognition system for 10 high-frequency letters (A, E, I, L, O, R, S, T, U, Y). MediaPipe extracts 21 hand landmarks per frame, fed into a custom 3-layer PyTorch MLP. Submitted for AAI3001: Computer Vision and Deep Learning.",
   problem:"Standardized Kaggle training images (professional lighting, controlled angles) caused domain adaptation issues with real consumer webcams. Standard classifiers also struggled with ASL class imbalance.",
   solution:"Built an end-to-end pipeline: MediaPipe Hand Landmarker extracts 21 anatomical landmarks (63-dimensional vector) per image, merged with 250 custom webcam samples collected under varied lighting. MLP (256-128-64, ReLU, 30% dropout) trained with Adam, ReduceLROnPlateau scheduler, and early stopping. Deployed via Flask for real-time webcam inference.",
   impact:["90.38% validation accuracy on 10-class ASL recognition","Custom dataset of 250 samples collected across varied real-world conditions improved generalization","Deployed as real-time Flask web app with webcam demo","Submitted for AAI3001 (Computer Vision and Deep Learning)"],
   tech:["PyTorch","MediaPipe","OpenCV","Flask","Python","NumPy","scikit-learn"],
   github:"https://github.com/mlemxy/asl-recognition",demo:""},

  {id:"churn",title:"Customer Churn Prediction",category:"ai-ml",emoji:"📊",
   image:"",
   tagline:"XGBoost + SMOTE-ENN · 81.28% recall · 0.8263 AUC · SHAP explainability",
   tags:["XGBoost","SMOTE-ENN","SHAP","Python","Scikit-learn"],
   metrics:[{v:"81.28%",l:"Recall"},{v:"0.8263",l:"AUC"},{v:"62.94%",l:"F1 Score"}],
   overview:"ML pipeline predicting customer churn in subscription-based industries. Compares 8 resampling techniques under identical conditions and uses SHAP for directional, per-customer churn explanations rather than just a probability score. Submitted for AAI2002, currently being extended toward real-time edge deployment on point-of-sale terminals.",
   problem:"Churn prediction is a class imbalance problem (only 26.58% of IBM Telco customers churned, 1:2.76 ratio). A naive classifier predicting everyone as retained still achieves high accuracy. An untuned XGBoost baseline hits only 52.05% recall, leaving nearly half of all churners undetected. Missing a churner forfeits remaining lifetime value and incurs reacquisition costs reported as 5 to 25 times the cost of retention.",
   solution:"Eight resampling techniques were compared. SMOTE-ENN produced the highest recall and cleaned noisy boundary samples. Dual GridSearchCV runs (scoring=f1 and scoring=recall) were run; the recall-tuned model (lr=0.01, depth=3, n=100, threshold=0.50) was selected. SHAP was chosen over XGBoost built-in importance and LIME for its directional per-customer waterfall explanations.",
   impact:["81.28% recall vs 52.05% untuned baseline (56% improvement)","0.8263 AUC, 62.94% F1 on held-out test set","Contract type identified as strongest churn driver (mean SHAP 0.7143): month-to-month customers significantly more likely to churn","Tenure and absence of online security/tech support ranked second and third globally","Being extended toward real-time edge deployment on POS terminals"],
   tech:["XGBoost","SMOTE-ENN","SHAP","Pandas","Scikit-learn","Matplotlib","Google Colab"],
   github:"https://github.com/mlemxy/churn-prediction",demo:"https://colab.research.google.com/github/mlemxy/churn-prediction/blob/main/main.ipynb"},

  {id:"apple",title:"Apple Quality Classification",category:"ai-ml",emoji:"🍎",
   image:"",
   tagline:"Multi-modal ML pipeline · tabular ensemble + ResNet50 transfer learning",
   tags:["TensorFlow","ResNet50","XGBoost","Transfer Learning","Python"],
   metrics:[{v:"Dual",l:"Track Pipeline"},{v:"ResNet50",l:"Transfer Learning"},{v:"Ensemble",l:"Soft Voting"}],
   overview:"Multi-modal ML pipeline for automated apple quality classification combining two independent tracks: a tabular ensemble for physical attributes and an image CNN with transfer learning for visual inspection. Submitted for INF2008: Machine Learning.",
   problem:"Apple quality assessment requires both physical measurement data and visual inspection. No single-modality model captures both signals. Standard CNNs trained from scratch may underperform on small agricultural datasets.",
   solution:"Tabular track: XGBoost, Logistic Regression, and Random Forest trained on physical attributes (size, weight, sweetness, crunchiness, juiciness, ripeness, acidity) from the Apple Quality dataset, tuned via GridSearchCV and combined into a soft-voting ensemble. Image track: custom CNN trained from scratch, followed by ResNet50 (ImageNet weights) with top layers replaced and fine-tuned on apple health vs rotten classification.",
   impact:["Two complementary classification tracks covering physical and visual quality signals","Soft-voting ensemble outperforms any single tabular model","ResNet50 transfer learning outperforms custom CNN on image track","Future work: multi-modal fusion combining both track outputs"],
   tech:["TensorFlow","ResNet50","XGBoost","Logistic Regression","Random Forest","scikit-learn","Pandas","Jupyter"],
   github:"https://github.com/mlemxy/apple-cut-classification",demo:"https://colab.research.google.com/github/mlemxy/apple-cut-classification/blob/main/main.ipynb"},

  {id:"peacesign",title:"PeaceSign",category:"ai-ml",emoji:"✌️",
   image:"assets/img/peacesign_microsoft_hackathon.png",
   tagline:"Microsoft Code; Without Barriers Grand Finalist · speech to sign language translator",
   tags:["Python","Flask","Azure Speech API","Accessibility","Hackathon"],
   metrics:[{v:"Grand",l:"Finalist"},{v:"Azure",l:"Cognitive Services"},{v:"Audio + Video",l:"Input Support"}],
   overview:"Web application bridging communication gaps for the hearing-impaired by translating speech into sign language. Built for the Microsoft Code; Without Barriers hackathon. Achieved Grand Finalist standing.",
   problem:"Hearing-impaired individuals face communication barriers in real-time spoken contexts. Existing tools lack practical, accessible, real-time speech-to-sign translation.",
   solution:"Flask web app using Azure Cognitive Services Speech SDK for transcription (supports both short-form audio and continuous long-form video). For each character transcribed, the corresponding ASL hand sign image is retrieved and compiled into a downloadable output. Handles both direct audio recordings and video files by extracting and processing the audio stream.",
   impact:["Grand Finalist at Microsoft Code; Without Barriers hackathon","Supports both audio and video input for broad accessibility","Translates continuous speech into compiled sign language output","Community-focused tool designed for the hearing-impaired"],
   tech:["Python","Flask","Azure Speech SDK","Azure Custom Vision","JavaScript","HTML/CSS","WTForms"],
   github:"https://github.com/mlemxy/PeaceSign",demo:""},

  {id:"suicide",title:"Suicide Rates Analysis",category:"ai-ml",emoji:"📈",
   image:"assets/img/suicide_rate_analysis_research.png",
   tagline:"EDA + NLP study · Singapore suicide determinants · SOS interventions",
   tags:["Python","NLTK","NLP","EDA","Reddit API","Pandas"],
   metrics:[{v:"EDA + NLP",l:"Methodology"},{v:"5",l:"Datasets"},{v:"2016-2021",l:"Time Range"}],
   overview:"Exploratory data analysis and NLP study investigating major social determinants of rising suicide rates in Singapore, and how they interact with Samaritans of Singapore (SOS) interventions. Submitted for CM2015: Programming with Data.",
   problem:"Singapore's suicide rates have been rising but the interplay between economic factors, mental health infrastructure, and third-sector interventions is not well-understood quantitatively. What social determinants drive risk, and does SOS intervention show measurable correlation?",
   solution:"Five datasets were merged on a shared 2016-2021 time axis (WHO/World Bank suicide data, MOH hospital admissions, MOM unemployment, SOS annual reports, and Reddit r/singapore posts via PRAW). EDA using Seaborn correlation heatmaps and distribution plots across demographic groups. NLP pipeline: tokenization, lemmatization, stopword removal via NLTK, then word cloud visualization of dominant public sentiment themes.",
   impact:["Unemployment showed high positive correlation with suicide risk calls (economic stress as key driver)","Community outreach correlated with rising rates (reactive relationship: SOS expands as rates climb)","Psychiatric hospital admissions showed negative correlation with suicide rates (access to care associated with reduced risk)","Reddit NLP surfaced mental health, community support, and personal crises as dominant public themes, consistent with quantitative findings"],
   tech:["Python","Pandas","NLTK","PRAW (Reddit API)","Seaborn","Matplotlib","Jupyter"],
   github:"https://github.com/mlemxy/suicide-analysis",demo:""},

  {id:"sim-auto",title:"SIM Email Automation",category:"professional",emoji:"⚡",
   image:"assets/img/automation.png",
   tagline:"99% process time reduction · 100 minutes to under 1 minute",
   tags:["Python","Automation","Email","Excel","Business Process"],
   metrics:[{v:"99%",l:"Time Saved"},{v:"<1 min",l:"From 100 min"},{v:"100",l:"Students per Batch"}],
   overview:"Python automation solution for voucher redemption email distribution at Singapore Institute of Management. Eliminated over 100 minutes of manual work per batch run for a team of 100 students.",
   problem:"Business development team manually processed and distributed voucher redemption emails one by one. The process was repetitive, error-prone, and consumed over 100 minutes per batch.",
   solution:"Python script integrating with the email system and Excel database to auto-generate personalized voucher emails and dispatch the full batch in under 1 minute. Zero manual intervention required after triggering the script.",
   impact:["99% reduction in process time per batch","Distribution time reduced from 100+ minutes to under 1 minute","Zero errors in voucher generation and delivery","Team time freed for higher-value business development work"],
   tech:["Python","Pandas","Email APIs","Excel Integration","Automation Scripting"],
   github:"",demo:""},

  {id:"locky",title:"Locky IoT System",category:"full-stack",emoji:"🔒",
   image:"assets/img/locky_iot_system.png",
   tagline:"Android smart locker · Firebase + Solidity blockchain · Bluetooth IoT · 9-month FYP",
   tags:["Java","Android","Firebase","Solidity","Blockchain","IoT"],
   metrics:[{v:"9 Months",l:"FYP Duration"},{v:"Blockchain",l:"Tamper-proof Logs"},{v:"Real-time",l:"Firebase Sync"}],
   overview:"Android application built as part of a 9-month multi-disciplinary final-year project spanning IoT, blockchain, and backend systems. My team owned the backend cycle: cloud data storage, user authentication, and blockchain integration. Separate teams handled the IoT hardware layer.",
   problem:"Traditional lockers lack secure authentication, real-time availability monitoring, and tamper-proof audit trails. Booking records can be altered or lost, creating accountability and security gaps.",
   solution:"Android app with Google Sign-In via Firebase Authentication. Firebase Realtime Database syncs locker availability from IoT sensor data in real time. Firebase Cloud Messaging (FCM) handles push notifications. Locker bookings are registered on-chain via a Solidity smart contract (BookingContract.sol, ^0.7.0) deployed on Ethereum, storing document number, receiver, locker ID, and booker identity in an immutable public mapping. Bluetooth connectivity links the app to the physical locker hardware via a gateway string interface.",
   impact:["Immutable blockchain-backed booking records via Solidity smart contract on Ethereum","Real-time locker availability synced from IoT sensors via Firebase Realtime Database","Secure Google Sign-In via Firebase Authentication","Push notifications via Firebase Cloud Messaging","Cross-functional delivery across IoT, backend, and blockchain teams over 9 months"],
   tech:["Java","Android Studio","Firebase Realtime DB","Firebase Auth","Firebase FCM","Solidity","Ethereum","Bluetooth"],
   github:"",demo:""},

  {id:"orangebot",title:"OrangeBot",category:"full-stack",emoji:"🤖",
   image:"assets/img/orangebot_discord_nlp.png",
   tagline:"NLP-powered Discord bot · multi-server deployment · SQLite persistence",
   tags:["Python","Discord.py","NLP","SQLite","Bot"],
   metrics:[{v:"Multi",l:"Server"},{v:"NLP",l:"Commands"},{v:"SQLite",l:"Persistence"}],
   overview:"Discord bot with natural language command parsing, automated moderation, scheduled tasks, and community engagement features across multiple servers.",
   problem:"Discord communities need intelligent automation beyond rigid prefix command syntax. Moderation and engagement tasks are repetitive and time-consuming for server admins.",
   solution:"discord.py bot with NLP for human-like command interpretation, SQLite for persistent state across sessions, automated moderation, and community engagement commands.",
   impact:["Deployed and active across multiple Discord servers","Natural language command understanding reduces friction for users","Automated moderation and engagement frees admin time","SQLite persistence maintains state across bot restarts"],
   tech:["Python","Discord.py","NLP","SQLite","Async Programming"],
   github:"",demo:""}
,
  {id:"archivist",title:"Archivist",category:"full-stack",emoji:"📚",
   image:"assets/img/archivist.png",
   tagline:"Chrome extension to bookmark and track AO3 fanfiction · macOS-style dashboard · Firebase sync",
   tags:["Chrome Extension","Firebase","IndexedDB","Chart.js","Vanilla JS","Manifest V3"],
   metrics:[{v:"MV3",l:"Chrome Extension"},{v:"Real-time",l:"Firebase Sync"},{v:"9 Charts",l:"Reading Stats"}],
   overview:"A personal Chrome extension built to learn web extension development. Bookmarks, annotates, and tracks AO3 fanfiction with a macOS-style desktop dashboard, chapter update notifications, AO3 reading history stats, and cross-device sync via Firebase. Plans to add ML-powered reading recommendations.",
   problem:"AO3 has no native bookmarking system with annotations, personal tags, or reading progress tracking. No way to visualise reading history or get notified when ongoing fics post new chapters.",
   solution:"Chrome extension (Manifest V3) using IndexedDB for local-first storage, a content script to scrape AO3 fic metadata, a macOS-style dashboard with draggable glassmorphic windows, Chart.js charts from scraped AO3 reading history, a 12-hour alarm-based chapter update checker, and Firebase Firestore for real-time cross-device bookmark sync.",
   impact:["Full macOS-style desktop UI with draggable windows, dock, menubar, and custom wallpaper","Real-time cross-device sync via Firebase Auth and Firestore","AO3 reading history scraper with smart caching and rate limiting (5-min pauses, exponential backoff)","9 Chart.js reading stat visualisations: top fandoms, ships, characters, ratings, and monthly activity","Chapter update checker: automatically flags ongoing fics with new chapters every 12 hours","Pulsing update badge on fic cards clears on click","Designed for public release — open source on GitHub"],
   tech:["Vanilla JS","Chrome MV3","IndexedDB","Firebase Auth","Firebase Firestore","Chart.js","html2canvas","esbuild"],
   github:"https://github.com/mlemxy/archivist",demo:""}
];